<?php
/**
 * @file
 * Password Have I Been Pwned?
 */

// Endpoint for HIBP password checks.
const PASSWORD_HAVEIBEENPWNED_DEFAULT_API_URL = 'https://api.pwnedpasswords.com/range/';

// User Agent to report to endpoint.
const PASSWORD_HAVEIBEENPWNED_DEFAULT_UA = 'Drupal (password_haveibeenpwned)';

// Timeout for requests to HIBP.
const PASSWORD_HAVEIBEENPWNED_DEFAULT_TIMEOUT = 2;

// Default result for HIBP checks which do no work (e.g. timeout, rate limited)
// N.B. "true" means that the password was found in the HIBP repository.
const PASSWORD_HAVEIBEENPWNED_FAILED_CHECK_DEFAULT = false;

// See the admin form for a description of this threshold.
const PASSWORD_HAVEIBEENPWNED_DEFAULT_PASSWORD_THRESHOLD = 10;

// Settings for policies.
const PASSWORD_HAVEIBEENPWNED_IGNORE = 0;
const PASSWORD_HAVEIBEENPWNED_WARN = 1;
const PASSWORD_HAVEIBEENPWNED_BLOCK = 2;

/**
 * Implements hook_menu().
 */
function password_haveibeenpwned_menu() {
  return array(
    'admin/config/people/password_haveibeenpwned' => array(
      'title' => 'Password Have I Been Pwned?',
      'description' => 'Configure Password Have I Been Pwned? settings.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('password_haveibeenpwned_admin_settings'),
      'access arguments' => array('administer site configuration'),
      'file' => 'password_haveibeenpwned.admin.inc',
    ),
  );
}

/**
 * Check a password with an API call to haveibeenpwned.
 *
 * @param string $password
 *   The plain text password.
 * @param boolean $return_count
 *   Return a count from the HIBP API.
 *
 * @return boolean | int
 *   Boolean: Whether the password should be considered compromised.
 *   Int: a count from the HIBP API.
 */
function password_haveibeenpwned_check_password($password, $return_count = false) {
  $hash = strtoupper(hash('sha1', ($password)));
  $hash_prefix = substr($hash, 0, 5);
  $hash_suffix = substr($hash, 5);

  $hibp_api_url = variable_get('password_haveibeenpwned_api_url', PASSWORD_HAVEIBEENPWNED_DEFAULT_API_URL);
  $ua = variable_get('password_haveibeenpwned_ua', PASSWORD_HAVEIBEENPWNED_DEFAULT_UA);
  $timeout = variable_get('password_haveibeenpwned_timeout', PASSWORD_HAVEIBEENPWNED_DEFAULT_TIMEOUT);
  $failed_check_default = variable_get('password_haveibeenpwned_failed_check_default', PASSWORD_HAVEIBEENPWNED_FAILED_CHECK_DEFAULT);
  $password_threshold = variable_get('password_haveibeenpwned_password_threshold', PASSWORD_HAVEIBEENPWNED_DEFAULT_PASSWORD_THRESHOLD);

  $result = drupal_http_request($hibp_api_url . $hash_prefix,
    array(
      'method' => 'GET',
      'timeout' => $timeout,
      'headers' => array(
        'User-Agent' => $ua,
      ),
    )
  );

  if (isset($result->error)) {
    // Log failed request to HIBP.
    $message = 'Request to !hibp_api_url failed. Responding with default for ';
    $message .= 'failed check (!hibp_failed_check_default) ';
    $message .= 'Details: @error_details';

    $details = $result->error;
    // @todo: is this necessary now that we only send the first 5 chars?
    // Ensure that we do not log actual hashes.
    $search = array($hash, "\n");
    $replace = array('**PASSWORD-HASH-REDACTED**', ' ');
    $details = str_replace($search, $replace, $details);



    $vars = array(
      '!hibp_api_url' => $hibp_api_url,
      '!hibp_failed_check_default' => ($failed_check_default ? 'true' : 'false'),
      '@error_details' => $details,
    );

    watchdog('password_haveibeenpwned', $message, $vars, WATCHDOG_ERROR);
    return $failed_check_default;
  }

  switch ($result->code) {
    case 200;
      $body = (string) $result->data;
      $lines = explode("\r\n", $body);
      foreach ($lines as $line) {
        list($api_hash_suffix, $count) = explode(':', $line);
        if ($hash_suffix == $api_hash_suffix) {
          if ($return_count) {
            return $count;
          }
          return ($count > $password_threshold);
        }
      }
      // The password is not considered compromised.
      return false;
      break;
    case 429:
      // Rate limit has been exceeded.
      watchdog('password_haveibeenpwned', 'HTTP status 429 returned; API calls hit rate limit.', array(), WATCHDOG_INFO);
      // Deliberately no break.
    default:
      // @todo: Log http errors (e.g. 401, 403, 50x); no exceptions are thrown.
      $status = $failed_check_default;
      break;
  }
  return $status;
}

/**
 * Implements hook_form_alter() for user_login_form and user_login_block.
 */
function password_haveibeenpwned_form_alter(&$form, $form_state, $form_id) {
  if (in_array($form_id, array('user_login', 'user_login_block'))) {
    $login_policy = variable_get('password_haveibeenpwned_login_policy', PASSWORD_HAVEIBEENPWNED_WARN);
    if ($login_policy == PASSWORD_HAVEIBEENPWNED_IGNORE) {
      return;
    }
    $form['#validate'][] = 'password_haveibeenpwned_user_login_form_validate';
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for user_register_form().
 */
function password_haveibeenpwned_form_user_register_form_alter(&$form, $form_state, $form_id) {
  $register_policy = variable_get('password_haveibeenpwned_register_policy', PASSWORD_HAVEIBEENPWNED_BLOCK);
  if ($register_policy == PASSWORD_HAVEIBEENPWNED_IGNORE) {
    return;
  }
  // Only add password validation if a password is going to be provided at registration.
  if (user_is_anonymous() and !variable_get('user_email_verification', TRUE)) {
    $form['#validate'][] = 'password_haveibeenpwned_user_register_form_validate';
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for user_profile_form().
 */
function password_haveibeenpwned_form_user_profile_form_alter(&$form, $form_state, $form_id) {
  $change_policy = variable_get('password_haveibeenpwned_change_policy', PASSWORD_HAVEIBEENPWNED_BLOCK);
  if ($change_policy == PASSWORD_HAVEIBEENPWNED_IGNORE) {
    return;
  }
  $form['#validate'][] = 'password_haveibeenpwned_user_form_validate';
}

/**
 * Validation for user_login_form().
 *
 * @param $form
 * @param $form_state
 */
function password_haveibeenpwned_user_login_form_validate($form, $form_state) {
  if (!isset($form_state['values']['pass'])) {
    return;
  }
  if (password_haveibeenpwned_check_password($form_state['values']['pass'])) {
    $login_policy = variable_get('password_haveibeenpwned_login_policy', PASSWORD_HAVEIBEENPWNED_WARN);
    switch ($login_policy) {
      case PASSWORD_HAVEIBEENPWNED_WARN:
        // At validation, the user is not yet authenticated so we can't provide an edit link.
        drupal_set_message(_password_haveibeenpwned_message_text('login_warning'), 'warning');
        break;
      case PASSWORD_HAVEIBEENPWNED_BLOCK:
        // Do we really want to be doing this?
        form_set_error('pass', _password_haveibeenpwned_message_text('login_blocked'));
        break;
    }
  }
}

/**
 * Validation for user_register_form().
 *
 * @param $form
 * @param $form_state
 */
function password_haveibeenpwned_user_register_form_validate($form, $form_state) {
  if (!isset($form_state['values']['pass'])) {
    return;
  }
  if (!($pass = _password_haveibeenpwned_extract_one_password($form_state['values']['pass']))) {
    return;
  }
  if (password_haveibeenpwned_check_password($pass)) {
    $register_policy = variable_get('password_haveibeenpwned_register_policy', PASSWORD_HAVEIBEENPWNED_BLOCK);
    switch ($register_policy) {
      case PASSWORD_HAVEIBEENPWNED_WARN:
        // At validation, the user is not yet authenticated so we can't provide an edit link.
        drupal_set_message(_password_haveibeenpwned_message_text('warning'), 'warning');
        break;
      case PASSWORD_HAVEIBEENPWNED_BLOCK:
        form_set_error('pass', _password_haveibeenpwned_message_text('register_blocked'));
        break;
    }
  }
}

/**
 * Validation for user_form().
 *
 * @param $form
 * @param $form_state
 */
function password_haveibeenpwned_user_form_validate($form, $form_state) {
  if (!isset($form_state['values']['pass'])) {
    return;
  }
  if (!($pass = _password_haveibeenpwned_extract_one_password($form_state['values']['pass']))) {
    return;
  }
  if (password_haveibeenpwned_check_password($pass)) {
    $change_policy = variable_get('password_haveibeenpwned_change_policy', PASSWORD_HAVEIBEENPWNED_BLOCK);
    switch ($change_policy) {
      case PASSWORD_HAVEIBEENPWNED_WARN:
        // At validation, the user is not yet authenticated so we can't provide an edit link.
        drupal_set_message(_password_haveibeenpwned_message_text('warning'), 'warning');
        break;
      case PASSWORD_HAVEIBEENPWNED_BLOCK:
        form_set_error('pass', _password_haveibeenpwned_message_text('change_blocked'));
        break;
    }
  }
}

/**
 * Extract individual password from pair of password confirmation inputs.
 *
 * @param array $passwords
 *
 * @return string OR boolean false if passwords did not match.
 */
function _password_haveibeenpwned_extract_one_password($passwords) {
  if (!is_array($passwords)) {
    return $passwords;
  }
  if (count(($password = array_unique($passwords))) > 1) {
    // Passwords didn't match.
    return false;
  }
  else {
    return array_pop($password);
  }
}

/**
 * Returns an overridable message string for a variable name.
 *
 * Similar to _user_mail_text().
 *
 * @return string
 */
function _password_haveibeenpwned_message_text($key, $replace = TRUE) {

  if ($admin_setting = variable_get('password_haveibeenpwned_message_' . $key, FALSE)) {
    // An admin setting overrides the default string.
    $text = $admin_setting;
  }
  else {
    // No override, return default string.
    switch ($key) {
      case 'warning':
        $text = t('The password you supplied appears in [password_haveibeenpwned:hibp_link], an online database of previous data breaches. You should choose a different password.');
        break;
      case 'login_warning':
        $text = t('Your current password appears in [password_haveibeenpwned:hibp_link], an online database of previous data breaches. You should change your password.');
        break;
      case 'login_blocked':
        $text = t('Your current password appears in [password_haveibeenpwned:hibp_link], an online database of previous data breaches. You need to [password_haveibeenpwned:password_reset].');
        break;
      case 'register_blocked':
        $text = t('The password you supplied appears in [password_haveibeenpwned:hibp_link], an online database of previous data breaches. You need to choose a different password for your account.');
        break;
      case 'change_blocked':
        $text = t('The new password you supplied appears in [password_haveibeenpwned:hibp_link], an online database of previous data breaches. You should choose a different password.');
        break;
    }
  }

  if ($replace) {
    $data = array();
    if (user_is_logged_in()) {
      $data['user'] = $GLOBALS['user'];
    }
    $text = token_replace($text, $data);
  }

  return $text;
}

/**
 * Implements hook_token_info().
 */
function password_haveibeenpwned_token_info() {
  $info['types'] = array(
    'password_haveibeenpwned' => array(
      'name' => t('Password Have I Been Pwned?'),
      'description' => t('Password Have I Been Pwned? tokens'),
    )
  );
  $info['tokens']['password_haveibeenpwned'] = array(
    'hibp_link' => array(
      'name' => t('HIBP link'),
      'description' => t('Link to the HIBP passwords site')
    ),
    'password_reset' => array(
      'name' => t('Password reset'),
      'description' => t('Link to the password reset form')
    )
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function password_haveibeenpwned_tokens($type, $tokens, $data = array(), $options = array()) {
  $replacements = array();
  if ($type == 'password_haveibeenpwned') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'hibp_link':
          $replacements[$original] = '<a href="https://haveibeenpwned.com/Passwords">HIBP</a>';
          break;
        case 'password_reset':
          $replacements[$original] = '<a href="/user/password">' . t('reset your password') . '</a>';
          break;
      }
    }
  }
  return $replacements;
}
