<?php

/**
 * @file
 * Install, update and uninstall functions for Password Have I Been Pwned?
 */

/**
 * Implements hook_uninstall().
 */
function password_haveibeenpwned_uninstall() {
  variable_del('password_haveibeenpwned_api_url');
  variable_del('password_haveibeenpwned_change_policy');
  variable_del('password_haveibeenpwned_failed_check_default');
  variable_del('password_haveibeenpwned_login_policy');
  variable_del('password_haveibeenpwned_message_change_blocked');
  variable_del('password_haveibeenpwned_message_login_blocked');
  variable_del('password_haveibeenpwned_message_login_warning');
  variable_del('password_haveibeenpwned_message_register_blocked');
  variable_del('password_haveibeenpwned_message_warning');
  variable_del('password_haveibeenpwned_password_threshold');
  variable_del('password_haveibeenpwned_register_policy');
  variable_del('password_haveibeenpwned_timeout');
  variable_del('password_haveibeenpwned_ua');
}
