<?php

/**
 * @file
 * Install, update and uninstall functions for Password Have I Been Pwned?
 */

/**
 * Implements hook_uninstall().
 */
function password_haveibeenpwned_uninstall() {
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_api_url');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_add_padding');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_change_policy');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_failed_check_default');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_login_policy');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_check_failed_login');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_message_change_blocked');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_message_login_blocked');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_message_login_warning');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_message_register_blocked');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_message_warning');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_password_threshold');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_register_policy');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_timeout');
  config_clear('password_haveibeenpwned.settings', 'password_haveibeenpwned_ua');
}

/**
 * Migrate password_haveibeenpwned variables to config.
 */
function password_haveibeenpwned_update_1000() {
  $config = config('password_haveibeenpwned.settings');
  $config->set('password_haveibeenpwned_login_policy', update_variable_get('password_haveibeenpwned_login_policy', 'PASSWORD_HAVEIBEENPWNED_WARN'));
  $config->set('password_haveibeenpwned_check_failed_login', update_variable_get('password_haveibeenpwned_check_failed_login', 'PASSWORD_HAVEIBEENPWNED_CHECK_FAILED_LOGIN'));
  $config->set('password_haveibeenpwned_change_policy', update_variable_get('password_haveibeenpwned_change_policy', 'PASSWORD_HAVEIBEENPWNED_BLOCK'));
  $config->set('password_haveibeenpwned_register_policy', update_variable_get('password_haveibeenpwned_register_policy', 'PASSWORD_HAVEIBEENPWNED_BLOCK'));
  $config->set('password_haveibeenpwned_password_threshold', update_variable_get('password_haveibeenpwned_password_threshold', 'PASSWORD_HAVEIBEENPWNED_DEFAULT_PASSWORD_THRESHOLD'));
  $config->set('password_haveibeenpwned_api_url', update_variable_get('password_haveibeenpwned_api_url', 'PASSWORD_HAVEIBEENPWNED_DEFAULT_API_URL'));
  $config->set('password_haveibeenpwned_ua', update_variable_get('password_haveibeenpwned_ua', 'PASSWORD_HAVEIBEENPWNED_DEFAULT_UA'));
  $config->set('password_haveibeenpwned_timeout', update_variable_get('password_haveibeenpwned_timeout', 'PASSWORD_HAVEIBEENPWNED_DEFAULT_TIMEOUT'));
  $config->set('password_haveibeenpwned_failed_check_default', update_variable_get('password_haveibeenpwned_failed_check_default', 'PASSWORD_HAVEIBEENPWNED_FAILED_CHECK_DEFAULT'));
  $config->set('password_haveibeenpwned_add_padding', update_variable_get('password_haveibeenpwned_add_padding', 'PASSWORD_HAVEIBEENPWNED_PADDING_DEFAULT'));
  $config->set('password_haveibeenpwned_message_key', update_variable_get('password_haveibeenpwned_message_key', 'dynamic variable in file /password_haveibeenpwned/password_haveibeenpwned.module line 308'));
  $config->save();

  update_variable_del('password_haveibeenpwned_login_policy');
  update_variable_del('password_haveibeenpwned_check_failed_login');
  update_variable_del('password_haveibeenpwned_change_policy');
  update_variable_del('password_haveibeenpwned_register_policy');
  update_variable_del('password_haveibeenpwned_password_threshold');
  update_variable_del('password_haveibeenpwned_api_url');
  update_variable_del('password_haveibeenpwned_ua');
  update_variable_del('password_haveibeenpwned_timeout');
  update_variable_del('password_haveibeenpwned_failed_check_default');
  update_variable_del('password_haveibeenpwned_add_padding');
  update_variable_del('password_haveibeenpwned_message_key');
}

/**
 * Implements hook_install().
 */
function password_haveibeenpwned_install() {
  // Dynamically generated variable data was detected.
  // /password_haveibeenpwned/password_haveibeenpwned.module line 308
}
