<?php

const API_URL = 'https://haveibeenpwned.com/api/v2/pwnedpassword/';

function pwned_password_validation_user_login(&$edit, $account) {
  if (isset($edit['input']['pass'])) {
    $hash = hash('sha1', $edit['input']['pass']);

    $result = drupal_http_request(API_URL . $hash);

    if ($result->code == 200) {
      drupal_set_message(t('The password you are using on this site has previously appeared in a data breach of another
      site. <strong>This is not related to a security incident on this site</strong>, however the fact that it has
      previously appeared elsewhere puts your account at risk. You should consider <a href="@user_profile_edit">changing
      your password</a> on this site as well as on any other site you may have used it.', [
        '@user_profile_edit' => url('user/' . $GLOBALS['user']->uid . '/edit'),
      ]), 'warning');
    }
  }
}
