<?php
/**
 * @file
 * Install, update and uninstall functions for pwned_passwords
 *
 */

/**
 * Implements hook_install().
 */
function pwned_passwords_install() {
  db_update('system')
  ->fields(array('weight' => 0,))
  ->condition('type', 'module')
  ->condition('name', 'pwned_passwords')
  ->execute();
}

/**
 * Implements hook_update_last_removed().
 */
function password_haveibeenpwned_update_last_removed() {
  return 7001;
}

/**
 * Convert variables from Drupal 7 to configuration.
 * Upgrade Drupal 7 sites with password_haveibeenpwned module installed.
 */
function pwned_passwords_update_1000() {
  $config = config('pwned_passwords.settings');
  $config->set('hibp_add_padding', update_variable_get('password_haveibeenpwned_add_padding'));
  $config->set('hibp_api_url', update_variable_get('password_haveibeenpwned_api_url'));
  $config->set('hibp_timeout', update_variable_get('password_haveibeenpwned_timeout'));
  $config->set('hibp_ua', update_variable_get('password_haveibeenpwned_ua'));
  $config->set('hibp_failed_check_default', update_variable_get('password_haveibeenpwned_failed_check_default'));
  $config->set('password_threshold', update_variable_get('password_haveibeenpwned_password_threshold'));
  $config->set('check_failed_login', update_variable_get('password_haveibeenpwned_check_failed_login'));
  $config->set('login_policy', update_variable_get('password_haveibeenpwned_login_policy'));
  $config->set('change_policy', update_variable_get('password_haveibeenpwned_change_policy'));
  $config->set('register_policy', update_variable_get('password_haveibeenpwned_register_policy'));
  $config->set('message_warning', update_variable_get('password_haveibeenpwned_message_warning'));
  $config->set('message_login_warning', update_variable_get('password_haveibeenpwned_message_login_warning'));
  $config->set('message_login_blocked', update_variable_get('password_haveibeenpwned_message_login_blocked'));
  $config->set('message_register_blocked', update_variable_get('password_haveibeenpwned_message_register_blocked'));
  $config->set('message_change_blocked', update_variable_get('password_haveibeenpwned_message_change_blocked'));
  $config->save();

  update_variable_del('password_haveibeenpwned_add_padding');
  update_variable_del('password_haveibeenpwned_api_url');
  update_variable_del('password_haveibeenpwned_timeout');
  update_variable_del('password_haveibeenpwned_ua');
  update_variable_del('password_haveibeenpwned_failed_check_default');
  update_variable_del('password_haveibeenpwned_password_threshold');
  update_variable_del('password_haveibeenpwned_check_failed_login');
  update_variable_del('password_haveibeenpwned_login_policy');
  update_variable_del('password_haveibeenpwned_change_policy');
  update_variable_del('password_haveibeenpwned_register_policy');
  update_variable_del('password_haveibeenpwned_message_warning');
  update_variable_del('password_haveibeenpwned_message_login_warning');
  update_variable_del('password_haveibeenpwned_message_login_blocked');
  update_variable_del('password_haveibeenpwned_message_register_blocked');
  update_variable_del('password_haveibeenpwned_message_change_blocked');
}
