<?php
/**
 * @file
 * Pwned passwords module
 * Have I Been Pwned?
 */

// Ask the HIBP API to add padding?
const PWNED_PASSWORDS_PADDING_DEFAULT = TRUE;

// Endpoint for HIBP password checks.
const PWNED_PASSWORDS_DEFAULT_API_URL = 'https://api.pwnedpasswords.com/range/';

// If the password given at login is incorrect, check it in HIBP?
const PWNED_PASSWORDS_CHECK_FAILED_LOGIN = FALSE;

// Default result for HIBP checks which fail (e.g. timeout, rate limited)
// N.B. "true" means that the password was found in the HIBP repository.
const PWNED_PASSWORDS_FAILED_CHECK_DEFAULT = FALSE;

// See the admin form for a description of this threshold.
const PWNED_PASSWORDS_DEFAULT_PASSWORD_THRESHOLD = 1;

// Timeout for requests to HIBP.
const PWNED_PASSWORDS_DEFAULT_TIMEOUT = 2;

// User Agent to report to endpoint.
const PWNED_PASSWORDS_DEFAULT_UA = 'Backdrop (pwned_passwords)';

// Settings for policies.
const PWNED_PASSWORDS_IGNORE = 0;
const PWNED_PASSWORDS_WARN = 1;
const PWNED_PASSWORDS_BLOCK = 2;

/**
 * Implements hook_menu().
 */
function pwned_passwords_menu() {
  return array(
    'admin/config/people/pwned_passwords' => array(
      'title' => 'Pwned Passwords settings',
      'description' => 'Configure pwned passwords Have I Been Pwned settings.',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('pwned_passwords_admin_settings'),
      'access arguments' => array('administer site configuration'),
      'file' => 'pwned_passwords.admin.inc',
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function pwned_passwords_config_info() {
  $prefixes['pwned_passwords.settings'] = array(
    'label' => t('Pwned passwords settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Check a password with an API call to haveibeenpwned.
 *
 * @param string $password
 *   The plain text password.
 * @param bool $return_count
 *   Return a count from the HIBP API.
 *
 * @return bool|int
 *   Boolean: Whether the password should be considered compromised.
 *   Int: a count from the HIBP API.
 */
function pwned_passwords_check_password($password, $return_count = FALSE) {
  $config = config('pwned_passwords.settings');
  $hash = strtoupper(hash('sha1', ($password)));
  $hash_prefix = substr($hash, 0, 5);
  $hash_suffix = substr($hash, 5);

  $hibp_api_url = $config->get('pwned_passwords_api_url');
  $ua = $config->get('pwned_passwords_ua');
  $timeout = $config->get('pwned_passwords_timeout');
  $failed_check_default = $config->get('pwned_passwords_failed_check_default');
  $password_threshold = $config->get('pwned_passwords_password_threshold');
  $hibp_padding = $config->get('pwned_passwords_add_padding') ? 'true' : 'false';

  $result = backdrop_http_request($hibp_api_url . $hash_prefix,
    array(
      'method' => 'GET',
      'timeout' => $timeout,
      'headers' => array(
        'User-Agent' => $ua,
        'Add-Padding' => $hibp_padding,
      ),
    )
  );

  if (isset($result->error)) {
    // Log failed request to HIBP.
    $message = 'Request to !hibp_api_url failed. Responding with default for ';
    $message .= 'failed check (!hibp_failed_check_default) ';
    $message .= 'Details: @error_details';

    $details = $result->error;
    // Ensure that we never log the actual password hash.
    $search = array($hash, "\n");
    $replace = array('**PASSWORD-HASH-REDACTED**', ' ');
    $details = str_replace($search, $replace, $details);

    $vars = array(
      '!hibp_api_url' => $hibp_api_url,
      '!hibp_failed_check_default' => ($failed_check_default ? 'true' : 'false'),
      '@error_details' => $details,
    );

    watchdog('pwned_passwords', $message, $vars, WATCHDOG_ERROR);
    return $failed_check_default;
  }

  switch ($result->code) {
    case 200:
      $body = (string) $result->data;
      $lines = explode("\r\n", $body);
      if ($hibp_padding === 'true') {
        $lines = array_filter($lines, '_pwned_passwords_filter_padding');
      }
      foreach ($lines as $line) {
        // phpcs:ignore SlevomatCodingStandard.PHP.ShortList
        list($api_hash_suffix, $count) = explode(':', $line);
        if ($hash_suffix === $api_hash_suffix) {
          if ($return_count) {
            return $count;
          }
          return ($count > $password_threshold);
        }
      }
      // The password is not considered compromised.
      $status = FALSE;
      break;

    case 429:
      // Rate limit has been exceeded.
      watchdog('pwned_passwords', 'HTTP status 429 returned; API calls hit rate limit.', array(), WATCHDOG_INFO);
      $status = $failed_check_default;
      break;

    default:
      watchdog('pwned_passwords', 'HTTP status @code returned.', array('@code' => $result->code), WATCHDOG_INFO);
      $status = $failed_check_default;
      break;
  }
  return $status;
}

/**
 * Callback to filter out padding results from the HIBP API.
 *
 * @see: https://www.troyhunt.com/enhancing-pwned-passwords-privacy-with-padding/
 */
function _pwned_passwords_filter_padding($entry) {
  return substr($entry, -2) !== ':0';
}

/**
 * Implements hook_form_alter() for user_login_form and user_login_block().
 */
function pwned_passwords_form_alter(&$form, $form_state, $form_id) {
  if (in_array($form_id, array('user_login', 'user_login_block'))) {
    $login_policy = config_get('pwned_passwords.settings', 'pwned_passwords_login_policy');
    if ($login_policy == PWNED_PASSWORDS_IGNORE) {
      return;
    }
    $form['#validate'][] = 'pwned_passwords_user_login_form_validate';
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for user_register_form().
 */
function pwned_passwords_form_user_register_form_alter(&$form, $form_state, $form_id) {
  $config = config('pwned_passwords.settings');
  $register_policy = $config->get('pwned_passwords_register_policy');
  if ($register_policy == PWNED_PASSWORDS_IGNORE) {
    return;
  }
  // Only add validation if a password is going to be provided at registration.
  if (user_is_anonymous() && !config_get('system.core', 'user_email_verification')) {
    $form['#validate'][] = 'pwned_passwords_user_register_form_validate';
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for user_profile_form().
 */
function pwned_passwords_form_user_profile_form_alter(&$form, $form_state, $form_id) {
  $change_policy = config_get('pwned_passwords.settings', 'pwned_passwords_change_policy');
  if ($change_policy == PWNED_PASSWORDS_IGNORE) {
    return;
  }
  $form['#validate'][] = 'pwned_passwords_user_form_validate';
}

/**
 * Validation for user_login_form().
 */
function pwned_passwords_user_login_form_validate($form, $form_state) {
  $config = config('pwned_passwords.settings');
  if (!isset($form_state['values']['pass'])) {
    return;
  }
  $errors = form_get_errors();
  $check_failed_logins = $config->get('pwned_passwords_check_failed_login');
  if (!$check_failed_logins && isset($errors['name'])) {
    return;
  }
  if (pwned_passwords_check_password($form_state['values']['pass'])) {
    $login_policy = $config->get('pwned_passwords_login_policy');
    switch ($login_policy) {
      case PWNED_PASSWORDS_WARN:
        // At validation, the user is not yet authenticated so we can't provide
        // an edit link.
        backdrop_set_message(_pwned_passwords_message_text('login_warning'), 'warning');
        break;

      case PWNED_PASSWORDS_BLOCK:
        // Do we really want to be doing this?
        form_set_error('pass', _pwned_passwords_message_text('login_blocked'));
        break;
    }
  }
}

/**
 * Validation for user_register_form().
 */
function pwned_passwords_user_register_form_validate($form, $form_state) {
  if (!isset($form_state['values']['pass'])) {
    return;
  }
  if (!($pass = _pwned_passwords_extract_one_password($form_state['values']['pass']))) {
    return;
  }
  if (pwned_passwords_check_password($pass)) {
    $register_policy = config_get('pwned_passwords.settings', 'pwned_passwords_register_policy');
    switch ($register_policy) {
      case PWNED_PASSWORDS_WARN:
        // At validation, the user is not yet authenticated so we can't provide
        // an edit link.
        backdrop_set_message(_pwned_passwords_message_text('warning'), 'warning');
        break;

      case PWNED_PASSWORDS_BLOCK:
        form_set_error('pass', _pwned_passwords_message_text('register_blocked'));
        break;
    }
  }
}

/**
 * Validation for user_form().
 */
function pwned_passwords_user_form_validate($form, $form_state) {
  if (!isset($form_state['values']['pass'])) {
    return;
  }
  if (!($pass = _pwned_passwords_extract_one_password($form_state['values']['pass']))) {
    return;
  }
  if (pwned_passwords_check_password($pass)) {
    $change_policy = config_get('pwned_passwords.settings', 'pwned_passwords_change_policy');
    switch ($change_policy) {
      case PWNED_PASSWORDS_WARN:
        // At validation, the user is not yet authenticated so we can't provide
        // an edit link.
        backdrop_set_message(_pwned_passwords_message_text('warning'), 'warning');
        break;

      case PWNED_PASSWORDS_BLOCK:
        form_set_error('pass', _pwned_passwords_message_text('change_blocked'));
        break;
    }
  }
}

/**
 * Extract individual password from pair of password confirmation inputs.
 *
 * @param array|string $passwords
 *   One or more passwords from a form submission.
 *
 * @return string|bool
 *   False if passwords did not match.
 */
function _pwned_passwords_extract_one_password($passwords) {
  if (!is_array($passwords)) {
    return $passwords;
  }
  if (count(($password = array_unique($passwords))) > 1) {
    // Passwords didn't match.
    return FALSE;
  }
  else {
    return array_pop($password);
  }
}

/**
 * Returns an overridable message string for a variable name.
 *
 * Similar to _user_mail_text().
 *
 * @param string $key
 *   The suffix for the variable name.
 * @param bool $replace
 *   Whether tokens in the text should be replaced.
 *
 * @return string
 *   Message text.
 */
function _pwned_passwords_message_text($key, $replace = TRUE) {
  $config = config('pwned_passwords.settings');

  if ($admin_setting = $config->get('pwned_passwords_message_' . $key)) {
    // An admin setting overrides the default string.
    $text = $admin_setting;
  }
  else {
    $check_failed_logins = $config->get('pwned_passwords_check_failed_login');
    // No override, return default string.
    switch ($key) {
      case 'warning':
        $text = t('The password provided appears in [pwned_passwords:hibp_link], an online database of previous data breaches. Please choose a different password.');
        break;

      case 'login_warning':
        if ($check_failed_logins) {
          $text = t('The password provided appears in [pwned_passwords:hibp_link], an online database of previous data breaches. Please choose a different password.');
        }
        else {
          $text = t('The password provided appears in [pwned_passwords:hibp_link], an online database of previous data breaches. Please choose a different password.');
        }
        break;

      case 'login_blocked':
        if ($check_failed_logins) {
          $text = t('The password provided appears in [pwned_passwords:hibp_link], an online database of previous data breaches. Please choose a different password or [pwned_passwords:password_reset].');
        }
        else {
          $text = t('The password provided appears in [pwned_passwords:hibp_link], an online database of previous data breaches. Please choose a different password or [pwned_passwords:password_reset].');
        }
        break;

      case 'register_blocked':
        $text = t('The password provided appears in [pwned_passwords:hibp_link], an online database of previous data breaches. Please choose a different password.');
        break;

      case 'change_blocked':
        $text = t('The password provided appears in [pwned_passwords:hibp_link], an online database of previous data breaches. Please choose a different password.');
        break;
    }
  }

  if ($replace) {
    $data = array();
    if (user_is_logged_in()) {
      $data['user'] = $GLOBALS['user'];
    }
    $text = token_replace($text, $data);
  }

  return $text;
}

/**
 * Implements hook_token_info().
 */
function pwned_passwords_token_info() {
  $info['types'] = array(
    'pwned_passwords' => array(
      'name' => t('Password Have I Been Pwned?'),
      'description' => t('Password Have I Been Pwned? tokens'),
    ),
  );
  $info['tokens']['pwned_passwords'] = array(
    'hibp_link' => array(
      'name' => t('HIBP link'),
      'description' => t('Link to the HIBP passwords site'),
    ),
    'password_reset' => array(
      'name' => t('Password reset'),
      'description' => t('Link to the password reset form'),
    ),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function pwned_passwords_tokens($type, $tokens, $data = array(), $options = array()) {
  $replacements = array();
  if ($type == 'pwned_passwords') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'hibp_link':
          $replacements[$original] = '<a href="https://haveibeenpwned.com/Passwords">HIBP</a>';
          break;

        case 'password_reset':
          $replacements[$original] = '<a href="/user/password">' . t('reset your password') . '</a>';
          break;
      }
    }
  }
  return $replacements;
}
