<?php

/**
 * @file
 * Install, update and uninstall functions for pwned_passwords
 *
 */

/**
 * Implements hook_uninstall().
 */
function pwned_passwords_uninstall() {
  config_clear('pwned_passwords.settings', 'pwned_passwords_api_url');
  config_clear('pwned_passwords.settings', 'pwned_passwords_add_padding');
  config_clear('pwned_passwords.settings', 'pwned_passwords_change_policy');
  config_clear('pwned_passwords.settings', 'pwned_passwords_failed_check_default');
  config_clear('pwned_passwords.settings', 'pwned_passwords_login_policy');
  config_clear('pwned_passwords.settings', 'pwned_passwords_check_failed_login');
  config_clear('pwned_passwords.settings', 'pwned_passwords_message_change_blocked');
  config_clear('pwned_passwords.settings', 'pwned_passwords_message_login_blocked');
  config_clear('pwned_passwords.settings', 'pwned_passwords_message_login_warning');
  config_clear('pwned_passwords.settings', 'pwned_passwords_message_register_blocked');
  config_clear('pwned_passwords.settings', 'pwned_passwords_message_warning');
  config_clear('pwned_passwords.settings', 'pwned_passwords_password_threshold');
  config_clear('pwned_passwords.settings', 'pwned_passwords_register_policy');
  config_clear('pwned_passwords.settings', 'pwned_passwords_timeout');
  config_clear('pwned_passwords.settings', 'pwned_passwords_ua');
}

/**
 * Migrate pwned_passwords variables to config.
 *
 * TODO: Strings for upgrades D7 Password Have I Been Pwned?
 */
function pwned_passwords_update_1000() {
  $config = config('pwned_passwords.settings');
  $config->set('pwned_passwords_login_policy', update_variable_get('pwned_passwords_login_policy', 'pwned_passwords_WARN'));
  $config->set('pwned_passwords_check_failed_login', update_variable_get('pwned_passwords_check_failed_login', 'pwned_passwords_CHECK_FAILED_LOGIN'));
  $config->set('pwned_passwords_change_policy', update_variable_get('pwned_passwords_change_policy', 'pwned_passwords_BLOCK'));
  $config->set('pwned_passwords_register_policy', update_variable_get('pwned_passwords_register_policy', 'pwned_passwords_BLOCK'));
  $config->set('pwned_passwords_password_threshold', update_variable_get('pwned_passwords_password_threshold', 'pwned_passwords_DEFAULT_PASSWORD_THRESHOLD'));
  $config->set('pwned_passwords_api_url', update_variable_get('pwned_passwords_api_url', 'pwned_passwords_DEFAULT_API_URL'));
  $config->set('pwned_passwords_ua', update_variable_get('pwned_passwords_ua', 'pwned_passwords_DEFAULT_UA'));
  $config->set('pwned_passwords_timeout', update_variable_get('pwned_passwords_timeout', 'pwned_passwords_DEFAULT_TIMEOUT'));
  $config->set('pwned_passwords_failed_check_default', update_variable_get('pwned_passwords_failed_check_default', 'pwned_passwords_FAILED_CHECK_DEFAULT'));
  $config->set('pwned_passwords_add_padding', update_variable_get('pwned_passwords_add_padding', 'pwned_passwords_PADDING_DEFAULT'));
  $config->set('pwned_passwords_message_key', update_variable_get('pwned_passwords_message_key', 'dynamic variable in file /pwned_passwords/pwned_passwords.module line 308'));
  $config->save();

  update_variable_del('pwned_passwords_login_policy');
  update_variable_del('pwned_passwords_check_failed_login');
  update_variable_del('pwned_passwords_change_policy');
  update_variable_del('pwned_passwords_register_policy');
  update_variable_del('pwned_passwords_password_threshold');
  update_variable_del('pwned_passwords_api_url');
  update_variable_del('pwned_passwords_ua');
  update_variable_del('pwned_passwords_timeout');
  update_variable_del('pwned_passwords_failed_check_default');
  update_variable_del('pwned_passwords_add_padding');
  update_variable_del('pwned_passwords_message_key');
}

/**
 * Implements hook_install().
 */
function pwned_passwords_install() {
  // TODO Dynamically generated variable data was detected.
  // /pwned_passwords/pwned_passwords.module line 308
}
