<?php

/**
 * @file
 * Password Have I Been Pwned? Tests.
 */

const HIBP_API_NEWLINE = "\r\n";

/**
 * Implements hook_menu().
 */
function password_haveibeenpwned_test_menu() {
  return array(
    'password_haveibeenpwned_test/mock_api' => array(
      'title' => 'Password Have I Been Pwned? Test mock API',
      'description' => 'A mock HIBP API endpoint for testing.',
      'page callback' => 'password_haveibeenpwned_test_mock_api',
      'page arguments' => array(2),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Page callback for mock HIBP API endpoint.
 */
function password_haveibeenpwned_test_mock_api($partial_hash) {
  switch ($partial_hash) {
    case 'AB87D':
      $password = 'monkey';
      $suffix = substr(strtoupper(hash('sha1', ($password))), 5);
      $suffix .= ':980209' . HIBP_API_NEWLINE;
      break;

    case 'B1B37':
      $password = 'qwerty';
      $suffix = substr(strtoupper(hash('sha1', ($password))), 5);
      $suffix .= ':3810555' . HIBP_API_NEWLINE;
      break;

    case 'CC915':
      $password = 'drupal';
      $suffix = substr(strtoupper(hash('sha1', ($password))), 5);
      $suffix .= ':55' . HIBP_API_NEWLINE;
      break;

    default:
      $suffix = '';
  }
  $before = $after = _password_haveibeenpwned_test_hash_suffixes(100);
  print trim($before . $suffix . $after);
  drupal_exit();
}

/**
 * Helper to generate hash suffixes for mock API responses.
 */
function _password_haveibeenpwned_test_hash_suffixes($count) {
  $suffixes = '';
  while ($count > 0) {
    $hash = substr(strtoupper(hash('sha1', ($count))), 5);
    $suffixes .= $hash . ':' . $count . HIBP_API_NEWLINE;
    $count--;
  }
  return $suffixes;
}

/**
 * Implements hook_form_FORM_ID_alter() for user_profile_form().
 */
function password_haveibeenpwned_test_form_user_profile_form_alter(&$form, $form_state, $form_id) {
  if (drupal_valid_test_ua()) {
    // Alter the user edit form to remove requirement for current password.
    if ($index = array_search('user_validate_current_pass', $form['#validate'])) {
      unset($form['#validate'][$index]);
    }
  }
}
