<?php
/**
 * @file
 * Install, update and uninstall functions for the password_haveibeenpwned_test module.
 *
 */


/**
 * Migrate password_haveibeenpwned_test variables to config.
 */
function password_haveibeenpwned_test_update_1000() {
  $config = config('password_haveibeenpwned_test.settings');
  $config->set('password_haveibeenpwned_test_log_headers', update_variable_get('password_haveibeenpwned_test_log_headers', array()));
  $config->save();

  update_variable_del('password_haveibeenpwned_test_log_headers');
}

/**
 * Implements hook_install().
 */
function password_haveibeenpwned_test_install() {
  // Dynamically generated variable data was detected.
}
