<?php
/**
 * @file
 * Install, update and uninstall functions for the pwned_passwords_test module.
 *
 */


/**
 * Migrate pwned_passwords_test variables to config.
 */
function pwned_passwords_test_update_1000() {
  $config = config('pwned_passwords_test.settings');
  $config->set('pwned_passwords_test_log_headers', update_variable_get('pwned_passwords_test_log_headers', array()));
  $config->save();

  update_variable_del('pwned_passwords_test_log_headers');
}

/**
 * Implements hook_install().
 */
function pwned_passwords_test_install() {
  // Dynamically generated variable data was detected.
}
