<?php

/**
 * @file
 * Password Have I Been Pwned? Tests.
 */

const PASSWORD_HAVEIBEENPWNED_TEST_HIBP_API_NEWLINE = "\r\n";

/**
 * Implements hook_menu().
 */
function password_haveibeenpwned_test_menu() {
  return array(
    'password_haveibeenpwned_test/mock_api' => array(
      'title' => 'Password Have I Been Pwned? Test mock API',
      'description' => 'A mock HIBP API endpoint for testing.',
      'page callback' => 'password_haveibeenpwned_test_mock_api',
      'page arguments' => array(2),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function password_haveibeenpwned_test_config_info() {
  $prefixes['password_haveibeenpwned_test.settings'] = array(
    'label' => t('Password Have I Been Pwned? settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Page callback for mock HIBP API endpoint.
 */
function password_haveibeenpwned_test_mock_api($partial_hash) {

  $padding = isset($_SERVER['HTTP_ADD_PADDING']) && strtolower($_SERVER['HTTP_ADD_PADDING']) === 'true';

  switch ($partial_hash) {
    case 'AB87D':
      $password = 'monkey';
      $suffix = substr(strtoupper(hash('sha1', ($password))), 5);
      $suffix .= ':980209' . PASSWORD_HAVEIBEENPWNED_TEST_HIBP_API_NEWLINE;
      break;

    case 'B1B37':
      $password = 'qwerty';
      $suffix = substr(strtoupper(hash('sha1', ($password))), 5);
      $suffix .= ':3810555' . PASSWORD_HAVEIBEENPWNED_TEST_HIBP_API_NEWLINE;
      break;

    case 'CC915':
      $password = 'backdrop';
      $suffix = substr(strtoupper(hash('sha1', ($password))), 5);
      $suffix .= ':55' . PASSWORD_HAVEIBEENPWNED_TEST_HIBP_API_NEWLINE;
      break;

    default:
      $suffix = '';
  }
  $before = $after = _password_haveibeenpwned_test_hash_suffixes(100);

  $padding_hashes = '';
  if ($padding) {
    // This random number does not need to be cryptographically secure.
    $padding_hashes = _password_haveibeenpwned_test_hash_suffixes(rand(599, 799), TRUE);
  }

  print trim($before . $suffix . $after . $padding_hashes);

  if (config_get('password_haveibeenpwned_test.settings', 'password_haveibeenpwned_test_log_headers') && isset($_SERVER['HTTP_ADD_PADDING'])) {
    $headers = array(
      'add-padding' => strtolower($_SERVER['HTTP_ADD_PADDING']),
    );
    $message = t('mock API endpoint received headers: !headers', array('!headers' => json_encode($headers)));
    watchdog('password_haveibeenpwned_test', $message);
  }

  backdrop_exit();
}

/**
 * Helper to generate hash suffixes for mock API responses.
 */
function _password_haveibeenpwned_test_hash_suffixes($count, $zero = FALSE) {
  $suffixes = '';
  while ($count > 0) {
    $hash = substr(strtoupper(hash('sha1', ($count))), 5);
    $num = $zero ? 0 : $count;
    $suffixes .= $hash . ':' . $num . PASSWORD_HAVEIBEENPWNED_TEST_HIBP_API_NEWLINE;
    $count--;
  }
  return $suffixes;
}

/**
 * Implements hook_form_FORM_ID_alter() for user_profile_form().
 */
function password_haveibeenpwned_test_form_user_profile_form_alter(&$form, $form_state, $form_id) {
  if (backdrop_valid_test_ua()) {
    // Alter the user edit form to remove requirement for current password.
    if ($index = array_search('user_validate_current_pass', $form['#validate'])) {
      unset($form['#validate'][$index]);
    }
  }
}

/**
 * Implements hook_autoload_info().
 */
function password_haveibeenpwned_test_autoload_info() {
  return array(
  );
}
